title: Заметки на память

url: "https://ronnietahn.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#remote_theme: rundocs/jekyll-rtd-theme
#remote_theme: just-the-docs/just-the-docs
remote_theme: ngzhio/jekyll-theme-hamilton

author: Дмитрий Волчков
avatar: rockonstage.jpg
#email:
location: Moscow, Russia
skin: midnight
lang: ru


search_enabled: true
search.heading_level: 2
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 10
search.rel_url: false
search.button: true

#plugins:
#  - jekyll-feed
