title: Your awesome title

url: "https://ronnietahn.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
#plugins:
#  - jekyll-feed
